---
output: github_document
title: Mini Data Analysis Milestone 2
---

# Welcome to your second (and last) milestone in your mini data analysis project

# Setup

Begin by loading your data and the tidyverse package below:

library(datateachr)
library(tidyverse)
library(dplyr)

# Task 1: Tidy your data (15 points)

A reminder of the definition of *tidy* data:

-   Each row is an **observation**
-   Each column is a **variable**
-   Each cell is a **value**

### 2.1 (2.5 points)

Based on the definition above, can you identify if your data is tidy or
untidy? Go through all your columns, or if you have \>8 variables, just
pick 8, and explain whether the data is untidy or tidy.

##Variables selected: ID, Diagnosis, radius_mean, texture_mean, perimeter_mean, area_mean, smoothness_mean, compactness_mean

#This data can be considered tidy because it meets the three requirements. Each row refers to one patient sample, each column considered here can be considered a variable, and each cell has an entry (as verified using is.na below)
is.na(cancer_sample$ID)
is.na(cancer_sample$radius_mean)
is.na(cancer_sample$texture_mean)
is.na(cancer_sample$perimeter_mean)
is.na(cancer_sample$area_mean)
is.na(cancer_sample$smoothness_mean)
is.na(cancer_sample$compactness_mean)

### 2.2 (5 points)

Now, if your data is tidy, untidy it! Then, tidy it back to it's
original state.

##since the dataset can be considered tidy, I will untidy the data first:
df %>%
pivot_wider(cancer_sample, names_from = Diagnosis, values_from = compactness_mean)



### 2.3 (7.5 points)

Now, you should be more familiar with your data, and also have made
progress in answering your research questions. Based on your interest,
and your analyses, pick 2 of the 4 research questions to continue your
analysis in the next four tasks:

```{=html}
<!-------------------------- Start your work below ---------------------------->
```
1.  *FILL_THIS_IN*
2.  *FILL_THIS_IN*

```{=html}
<!----------------------------------------------------------------------------->
```
Explain your decision for choosing the above two research questions.

```{=html}
<!--------------------------- Start your work below --------------------------->
```
```{=html}
<!----------------------------------------------------------------------------->
```
Now, try to choose a version of your data that you think will be
appropriate to answer these 2 questions. Use between 4 and 8 functions
that we've covered so far (i.e. by filtering, cleaning, tidy'ing,
dropping irrelevant columns, etc.).

```{=html}
<!--------------------------- Start your work below --------------------------->
```
```{=html}
<!----------------------------------------------------------------------------->
```
# Task 2: Special Data Types (10)

For this exercise, you'll be choosing two of the three tasks below --
both tasks that you choose are worth 5 points each.

But first, tasks 1 and 2 below ask you to modify a plot you made in a
previous milestone. The plot you choose should involve plotting across
at least three groups (whether by facetting, or using an aesthetic like
colour). Place this plot below (you're allowed to modify the plot if
you'd like). If you don't have such a plot, you'll need to make one.
Place the code for your plot below.

```{=html}
<!-------------------------- Start your work below ---------------------------->
```
```{=html}
<!----------------------------------------------------------------------------->
```
Now, choose two of the following tasks.

1.  Produce a new plot that reorders a factor in your original plot,
    using the `forcats` package (3 points). Then, in a sentence or two,
    briefly explain why you chose this ordering (1 point here for
    demonstrating understanding of the reordering, and 1 point for
    demonstrating some justification for the reordering, which could be
    subtle or speculative.)

2.  Produce a new plot that groups some factor levels together into an
    "other" category (or something similar), using the `forcats` package
    (3 points). Then, in a sentence or two, briefly explain why you
    chose this grouping (1 point here for demonstrating understanding of
    the grouping, and 1 point for demonstrating some justification for
    the grouping, which could be subtle or speculative.)

3.  If your data has some sort of time-based column like a date (but
    something more granular than just a year):

    1.  Make a new column that uses a function from the `lubridate` or
        `tsibble` package to modify your original time-based column. (3
        points)

        -   Note that you might first have to *make* a time-based column
            using a function like `ymd()`, but this doesn't count.
        -   Examples of something you might do here: extract the day of
            the year from a date, or extract the weekday, or let 24
            hours elapse on your dates.

    2.  Then, in a sentence or two, explain how your new column might be
        useful in exploring a research question. (1 point for
        demonstrating understanding of the function you used, and 1
        point for your justification, which could be subtle or
        speculative).

        -   For example, you could say something like "Investigating the
            day of the week might be insightful because penguins don't
            work on weekends, and so may respond differently".

```{=html}
<!-------------------------- Start your work below ---------------------------->
```
**Task Number**: FILL_THIS_IN

```{=html}
<!----------------------------------------------------------------------------->
```
```{=html}
<!-------------------------- Start your work below ---------------------------->
```
**Task Number**: FILL_THIS_IN

```{=html}
<!----------------------------------------------------------------------------->
```
# Task 3: Modelling

## 2.0 (no points)

Pick a research question, and pick a variable of interest (we'll call it
"Y") that's relevant to the research question. Indicate these.

```{=html}
<!-------------------------- Start your work below ---------------------------->
```
**Research Question**: FILL_THIS_IN

**Variable of interest**: FILL_THIS_IN

```{=html}
<!----------------------------------------------------------------------------->
```
## 2.1 (5 points)

Fit a model or run a hypothesis test that provides insight on this
variable with respect to the research question. Store the model object
as a variable, and print its output to screen. We'll omit having to
justify your choice, because we don't expect you to know about model
specifics in STAT 545.

-   **Note**: It's OK if you don't know how these models/tests work.
    Here are some examples of things you can do here, but the sky's the
    limit.

    -   You could fit a model that makes predictions on Y using another
        variable, by using the `lm()` function.
    -   You could test whether the mean of Y equals 0 using `t.test()`,
        or maybe the mean across two groups are different using
        `t.test()`, or maybe the mean across multiple groups are
        different using `anova()` (you may have to pivot your data for
        the latter two).
    -   You could use `lm()` to test for significance of regression.

```{=html}
<!-------------------------- Start your work below ---------------------------->
```
```{=html}
<!----------------------------------------------------------------------------->
```
## 2.2 (5 points)

Produce something relevant from your fitted model: either predictions on
Y, or a single value like a regression coefficient or a p-value.

-   Be sure to indicate in writing what you chose to produce.
-   Your code should either output a tibble (in which case you should
    indicate the column that contains the thing you're looking for), or
    the thing you're looking for itself.
-   Obtain your results using the `broom` package if possible. If your
    model is not compatible with the broom function you're needing, then
    you can obtain your results by some other means, but first indicate
    which broom function is not compatible.

```{=html}
<!-------------------------- Start your work below ---------------------------->
```
```{=html}
<!----------------------------------------------------------------------------->
```
# Task 4: Reading and writing data

Get set up for this exercise by making a folder called `output` in the
top level of your project folder / repository. You'll be saving things
there.

## 3.1 (5 points)

Take a summary table that you made from Milestone 1 (Task 4.2), and
write it as a csv file in your `output` folder. Use the `here::here()`
function.

-   **Robustness criteria**: You should be able to move your Mini
    Project repository / project folder to some other location on your
    computer, or move this very Rmd file to another location within your
    project repository / folder, and your code should still work.
-   **Reproducibility criteria**: You should be able to delete the csv
    file, and remake it simply by knitting this Rmd file.

```{=html}
<!-------------------------- Start your work below ---------------------------->
```
```{=html}
<!----------------------------------------------------------------------------->
```
## 3.2 (5 points)

Write your model object from Task 3 to an R binary file (an RDS), and
load it again. Be sure to save the binary file in your `output` folder.
Use the functions `saveRDS()` and `readRDS()`.

-   The same robustness and reproducibility criteria as in 3.1 apply
    here.

```{=html}
<!-------------------------- Start your work below ---------------------------->
```
```{=html}
<!----------------------------------------------------------------------------->
```
# Tidy Repository

Now that this is your last milestone, your entire project repository
should be organized. Here are the criteria we're looking for.

## Main README (3 points)

There should be a file named `README.md` at the top level of your
repository. Its contents should automatically appear when you visit the
repository on GitHub.

Minimum contents of the README file:

-   In a sentence or two, explains what this repository is, so that
    future-you or someone else stumbling on your repository can be
    oriented to the repository.
-   In a sentence or two (or more??), briefly explains how to engage
    with the repository. You can assume the person reading knows the
    material from STAT 545A. Basically, if a visitor to your repository
    wants to explore your project, what should they know?

Once you get in the habit of making README files, and seeing more README
files in other projects, you'll wonder how you ever got by without them!
They are tremendously helpful.

## File and Folder structure (3 points)

You should have at least three folders in the top level of your
repository: one for each milestone, and one output folder. If there are
any other folders, these are explained in the main README.

Each milestone document is contained in its respective folder, and
nowhere else.

Every level-1 folder (that is, the ones stored in the top level, like
"Milestone1" and "output") has a `README` file, explaining in a sentence
or two what is in the folder, in plain language (it's enough to say
something like "This folder contains the source for Milestone 1").

## Output (2 points)

All output is recent and relevant:

-   All Rmd files have been `knit`ted to their output, and all data
    files saved from Task 4 above appear in the `output` folder.
-   All of these output files are up-to-date -- that is, they haven't
    fallen behind after the source (Rmd) files have been updated.
-   There should be no relic output files. For example, if you were
    knitting an Rmd to html, but then changed the output to be only a
    markdown file, then the html file is a relic and should be deleted.

Our recommendation: delete all output files, and re-knit each
milestone's Rmd file, so that everything is up to date and relevant.

PS: there's a way where you can run all project code using a single
command, instead of clicking "knit" three times. More on this in STAT
545B!

## Error-free code (1 point)

This Milestone 1 document knits error-free, and the Milestone 2 document
knits error-free.

Plots failing to show up on Github in the .md counts as an error here.
So does the entire .md failing to show up on Github in the .md ("Sorry
about that, but we can't show files that are this big right now").

## Tagged release (1 point)

You've tagged a release for Milestone 1, and you've tagged a release for
Milestone 2.

### Attribution

Thanks to Victor Yuan for mostly putting this together.
